# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\create_menu\create_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(392, 282)
        Form.setStyleSheet("background-color: rgb(148, 150, 255);\n"
"border-left-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.bt_sc = QtWidgets.QPushButton(Form)
        self.bt_sc.setGeometry(QtCore.QRect(20, 180, 171, 61))
        self.bt_sc.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(112, 107, 255);")
        self.bt_sc.setObjectName("bt_sc")
        self.bt_np = QtWidgets.QPushButton(Form)
        self.bt_np.setGeometry(QtCore.QRect(250, 180, 121, 61))
        self.bt_np.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(112, 107, 255);")
        self.bt_np.setObjectName("bt_np")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 50, 321, 61))
        self.label.setStyleSheet("font: 24pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(112, 107, 255);")
        self.label.setObjectName("label")
        self.number_of_pages = QtWidgets.QLabel(Form)
        self.number_of_pages.setGeometry(QtCore.QRect(320, 62, 31, 41))
        self.number_of_pages.setStyleSheet("font: 24pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(112, 107, 255);")
        self.number_of_pages.setObjectName("number_of_pages")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 391, 281))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(4)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.bt_sc.raise_()
        self.bt_np.raise_()
        self.label.raise_()
        self.number_of_pages.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_sc.setText(_translate("Form", "Save and Close"))
        self.bt_np.setText(_translate("Form", "New Page"))
        self.label.setText(_translate("Form", "  Number of pages:"))
        self.number_of_pages.setText(_translate("Form", "0"))
