# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\create_menu\create_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(723, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(800, 800))
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 80, 621, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.book_title = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.book_title.setMaximumSize(QtCore.QSize(500, 50))
        self.book_title.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(255, 255, 255);")
        self.book_title.setObjectName("book_title")
        self.horizontalLayout_8.addWidget(self.book_title)
        self.pb_upload = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pb_upload.setMaximumSize(QtCore.QSize(250, 50))
        self.pb_upload.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.pb_upload.setObjectName("pb_upload")
        self.horizontalLayout_8.addWidget(self.pb_upload)
        self.pb_np = QtWidgets.QPushButton(Form)
        self.pb_np.setGeometry(QtCore.QRect(560, 440, 141, 61))
        self.pb_np.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.pb_np.setObjectName("pb_np")
        self.pb_back = QtWidgets.QPushButton(Form)
        self.pb_back.setGeometry(QtCore.QRect(20, 440, 141, 61))
        self.pb_back.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.pb_back.setObjectName("pb_back")
        self.preview = QtWidgets.QLabel(Form)
        self.preview.setGeometry(QtCore.QRect(30, 180, 47, 69))
        self.preview.setMaximumSize(QtCore.QSize(100, 100))
        self.preview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.preview.setScaledContents(True)
        self.preview.setObjectName("preview")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.book_title.setPlaceholderText(_translate("Form", "Book Title"))
        self.pb_upload.setText(_translate("Form", "Upload Cover Image"))
        self.pb_np.setText(_translate("Form", "Next"))
        self.pb_back.setText(_translate("Form", "Cancel"))
        self.preview.setText(_translate("Form", "TextLabel"))
