# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\create_menu\create_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(577, 407)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(210, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pb_np = QtWidgets.QPushButton(Form)
        self.pb_np.setGeometry(QtCore.QRect(460, 220, 75, 23))
        self.pb_np.setObjectName("pb_np")
        self.pb_back = QtWidgets.QPushButton(Form)
        self.pb_back.setGeometry(QtCore.QRect(190, 240, 75, 23))
        self.pb_back.setObjectName("pb_back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_np.setText(_translate("Form", "Next"))
        self.pb_back.setText(_translate("Form", "Cancel"))
