# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\create_menu\create_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(400, 300)
        self.bt_sc = QtWidgets.QPushButton(Form)
        self.bt_sc.setGeometry(QtCore.QRect(30, 180, 111, 31))
        self.bt_sc.setObjectName("bt_sc")
        self.bt_np = QtWidgets.QPushButton(Form)
        self.bt_np.setGeometry(QtCore.QRect(270, 190, 75, 23))
        self.bt_np.setObjectName("bt_np")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 100, 221, 61))
        self.label.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_sc.setText(_translate("Form", "Save and Close"))
        self.bt_np.setText(_translate("Form", "New Page"))
        self.label.setText(_translate("Form", "TextLabel"))
