# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\help_menu\help_menu - Copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(633, 453)
        Form.setStyleSheet("background-color: rgb(148, 150, 255);\n"
"border-left-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 631, 451))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(4)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 90, 291, 61))
        self.label.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 101, 41))
        self.label_3.setStyleSheet("font: 30pt \"Franklin Gothic Demi\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 431, 61))
        self.label_4.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 291, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("d:\\SRI\\HandSignLanguage\\menus\\help_menu\\../imagens_menus/help_1.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(330, 240, 271, 191))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("d:\\SRI\\HandSignLanguage\\menus\\help_menu\\../imagens_menus/help_2.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "1º Choose a Book to Read"))
        self.label_3.setText(_translate("Form", "HELP"))
        self.label_4.setText(_translate("Form", "2º Clique on the Words to Watch a Video \n"
"for SignLanguage"))
