# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\main_menu\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(785, 590)
        Form.setStyleSheet("")
        self.pb_read = QtWidgets.QPushButton(Form)
        self.pb_read.setGeometry(QtCore.QRect(310, 320, 161, 81))
        self.pb_read.setStyleSheet("font: 24pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);\n"
"")
        self.pb_read.setAutoDefault(False)
        self.pb_read.setDefault(False)
        self.pb_read.setFlat(False)
        self.pb_read.setObjectName("pb_read")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 420, 161, 81))
        self.pushButton_2.setStyleSheet("font: 24pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 420, 161, 81))
        self.pushButton_3.setStyleSheet("font: 24pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 110, 481, 221))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("d:\\SRI\\HandSignLanguage\\menus\\main_menu\\../imagens_menus/imagem_junta_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 10, 481, 151))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("d:\\SRI\\HandSignLanguage\\menus\\main_menu\\../imagens_menus/titulo_png.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.pb_read.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_read.setText(_translate("Form", "Read"))
        self.pushButton_2.setText(_translate("Form", "Exit"))
        self.pushButton_3.setText(_translate("Form", "Help"))
import resource_file_rc
