# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\read_menu\read_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(738, 498)
        self.body = QtWidgets.QTabWidget(widget)
        self.body.setGeometry(QtCore.QRect(40, 80, 641, 391))
        self.body.setTabPosition(QtWidgets.QTabWidget.South)
        self.body.setElideMode(QtCore.Qt.ElideNone)
        self.body.setDocumentMode(True)
        self.body.setObjectName("body")
        self.back = QtWidgets.QPushButton(widget)
        self.back.setGeometry(QtCore.QRect(0, 0, 100, 38))
        self.back.setMaximumSize(QtCore.QSize(100, 50))
        self.back.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.back.setObjectName("back")

        self.retranslateUi(widget)
        self.body.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.back.setText(_translate("widget", "Back"))
