# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\text_menu\text_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 590)
        self.bt_next = QtWidgets.QPushButton(Form)
        self.bt_next.setGeometry(QtCore.QRect(560, 440, 141, 61))
        self.bt_next.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_next.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.bt_next.setObjectName("bt_next")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 701, 261))
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.upload = QtWidgets.QPushButton(Form)
        self.upload.setGeometry(QtCore.QRect(250, 290, 211, 51))
        self.upload.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.upload.setObjectName("upload")
        self.preview = QtWidgets.QLabel(Form)
        self.preview.setGeometry(QtCore.QRect(40, 300, 181, 141))
        self.preview.setScaledContents(True)
        self.preview.setObjectName("preview")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_next.setText(_translate("Form", "Next"))
        self.upload.setText(_translate("Form", "Upload illustration"))
        self.preview.setText(_translate("Form", "TextLabel"))
