# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\words_menu\words_item_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(590, 124)
        Form.setMinimumSize(QtCore.QSize(570, 0))
        Form.setMaximumSize(QtCore.QSize(590, 16777215))
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 581, 90))
        self.frame_2.setStyleSheet("background-color: rgb(148, 150, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(340, 30, 51, 30))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.le_word = QtWidgets.QLineEdit(self.frame_2)
        self.le_word.setEnabled(False)
        self.le_word.setGeometry(QtCore.QRect(40, 30, 300, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_word.sizePolicy().hasHeightForWidth())
        self.le_word.setSizePolicy(sizePolicy)
        self.le_word.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.le_word.setObjectName("le_word")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(30, 30, 10, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pb_config = QtWidgets.QToolButton(self.frame_2)
        self.pb_config.setGeometry(QtCore.QRect(395, 29, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_config.sizePolicy().hasHeightForWidth())
        self.pb_config.setSizePolicy(sizePolicy)
        self.pb_config.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.pb_config.setObjectName("pb_config")
        self.bt_delete = QtWidgets.QToolButton(self.frame_2)
        self.bt_delete.setGeometry(QtCore.QRect(530, 29, 41, 31))
        self.bt_delete.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.bt_delete.setObjectName("bt_delete")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_config.setText(_translate("Form", "..."))
        self.bt_delete.setText(_translate("Form", "X"))
