# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SRI\HandSignLanguage\menus\words_menu\words_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 591)
        self.bt_prev = QtWidgets.QPushButton(Form)
        self.bt_prev.setGeometry(QtCore.QRect(30, 440, 141, 61))
        self.bt_prev.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.bt_prev.setObjectName("bt_prev")
        self.bt_next = QtWidgets.QPushButton(Form)
        self.bt_next.setGeometry(QtCore.QRect(560, 440, 141, 61))
        self.bt_next.setStyleSheet("font: 18pt \"Franklin Gothic Demi\";\n"
"background-color: rgb(148, 150, 255);")
        self.bt_next.setObjectName("bt_next")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(40, 20, 650, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(650, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(650, 16777215))
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_prev.setText(_translate("Form", "Back"))
        self.bt_next.setText(_translate("Form", "Next"))
        self.listWidget.setSortingEnabled(False)
